apiVersion: v1
kind: Pod
metadata:
  name: mongo-prac
spec:
  containers:
  - name: mongo-prac
    image: "mongo"
    volumeMounts:
    - name: mongo-data
      mountPath: /scrub
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongo-data
    hostPath:
    path: /any/path/it/will/be/replaced