apiVersion: v1
kind: Pod
metadata:
  name: volumes-configmap
  labels:
    purpose: volumes-configmap
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config