#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#

# Turn on debug logging to show ConditionEvaluationReport :
#debug: true

##---------------------------------------------------------------------------##
spring:


  ##---------------------------------------------------------------------------##
  ## Thymeleaf configuration:
#  thymeleaf:
#    cache: false
#    mode: HTML


  ##---------------------------------------------------------------------------##
  ## H2 Admin Servlet Configuration:
  ## Note: See SecurityConfig.java for configuration:

  # http://localhost:8080/admin/h2
  h2.console.enabled: false

  ##---------------------------------------------------------------------------##
  ## Datasource Configuration:
  datasource:
    url: jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

    # These items are needed for testing:
    continue-on-error: true
    generate-unique-name: true

##---------------------------------------------------------------------------##
## Actuators:
## https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
## To expose all endpoints (be aware before exposing all endpoints for production)
# http://localhost:8080/actuator
# http://localhost:8080/actuator/beans
# http://localhost:8080/actuator/mappings
management:
  endpoints:
    web:
      #      base-path: /admin/actuator
      exposure:
        include: '*'


##---------------------------------------------------------------------------##
## Logging Configuration:
logging:
  level:
    io:
      baselogic:
        testloglevel: INFO

##---------------------------------------------------------------------------##
