#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#

# ENABLE for debug logging to show ConditionEvaluationReport :
debug: false

##---------------------------------------------------------------------------##
# Configuring TLS in Tomcat in Spring Boot
server:
  port: 8443
  ssl:
    key-store: "classpath:keys/event_manager_clientauth.p12"
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: event_manager_client

    protocol: TLS
    enabled: true

    trust-store: "classpath:keys/event_manager.truststore"
    trust-store-password: changeit
    client-auth: need


##---------------------------------------------------------------------------##
spring:


  ##---------------------------------------------------------------------------##
  ## H2 Admin Servlet Configuration:
  ## Note: See SecurityConfig.java for configuration:

  # http://localhost:8080/admin/h2
  h2.console.enabled: true

  ##---------------------------------------------------------------------------##
  ## Datasource Configuration:
  ## see io.baselogic.springsecurity.configuration.DataSourceConfig

  datasource:
    ## Default URL for embedded is 'jdbc:h2:mem:testdb'
    url: jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

    schema:
      - classpath:/schema.sql

    data:
      - classpath:/data.sql

    # These items are needed for testing:
    continue-on-error: true
    generate-unique-name: false



  ##---------------------------------------------------------------------------##
  ## JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

      # These properties are only needed to dump the JPA generated ddl to a file:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: target/create.sql


##---------------------------------------------------------------------------##
## Actuators:
## https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
## To expose all endpoints (be aware before exposing all endpoints for production)
# http://localhost:8080/actuator
# http://localhost:8080/actuator/beans
# http://localhost:8080/actuator/mappings
management:
  endpoints:
    web:
      #      base-path: /admin/actuator
      exposure:
        include: '*'


##---------------------------------------------------------------------------##
## Logging Configuration:
logging:
  level:
    io:
      baselogic:
        testloglevel: INFO

logging.level.org.hibernate.SQL: INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: INFO


##---------------------------------------------------------------------------##
