apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resource
spec:
  selector:
    matchLabels:
      app: nginx-resource
  template:
    metadata:
      labels:
        app: nginx-resource
    spec:
      containers:
      - name: nginx-resource
        image: nginx
        resources:
          requests:
            memory: "200Mi"
            cpu: "1m"
          limits:
            memory: "400Mi"
            cpu: "2m"
        ports:
        - containerPort: 80
