apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  labels:
    app: alpine-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: alpine-deployment
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alpine-deployment
    spec:
      containers:
      - name: alpine
        image: alpine:3.4
        ports:
        - containerPort: 8080
