GET http://localhost:8080/customers

###

GET http://localhost:8080/customers/1

###

GET http://localhost:8080/customers/5

###

POST http://localhost:8080/customers
Content-Type: application/json

{
  "name": "Saul"
}

###

DELETE http://localhost:8080/customers/5

###

PATCH http://localhost:8080/customers/6
Content-Type: application/json

{
  "name": "updated"
}

###
