GET http://localhost:8080/customers

###

GET http://localhost:8080/customers/3

###

POST http://localhost:8080/customers
Content-Type: application/json

{
  "id": 4,
  "name": "Tom"
}

###

DELETE http://localhost:8080/customers/1

###

PATCH http://localhost:8080/customers/1
Content-Type: application/json

{
  "id": 6,
  "name": "updated"
}

###