apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
  labels:
    purpose: configmap-demo
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      valueFrom:
        configMapKeyRef:
          name: test-map
          key: test