spring:
  application:
    name: netflix-zuul-api-gateway-server

server:
  port: 8765
  ssl:
    enabled: true
    key-alias: ssltest
    key-store-password: your_password
    key-store: /your/path/ssltest.jks

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 8765

zuul:
  sensitive-headers: Cookie, Set-Cookie
  ssl-hostname-validation-enabled: false
